name: Player Initialization

on:
  workflow_dispatch:
    inputs:
      displayName:
        description: 'The display name of the player'
        required: true
        default: ''
      tag:
        description: 'The tag of the player'
        required: true
        default: ''
      region:
        description: 'The region of the player'
        required: true
        default: ''

concurrency:
  group: "player-initialization-queue"
  cancel-in-progress: false


run-name: "Adding ${{ inputs.region }} user: ${{ inputs.displayName }}#${{ inputs.tag }}"

jobs:
  init_player:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/actions/requirements.txt


      - name: Run initialization script
        env:
            REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
            MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python backend/actions/create_user_prefetch.py "${{ github.event.inputs.displayName }}" "${{ github.event.inputs.tag }}" "${{ github.event.inputs.region }}"
